[package]
name = "eb-interface-rs"
version = "0.0.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = { version = "~1", default-features = false, features = [] }

[dev-dependencies]
rust_decimal_macros = { version = "~1", default-features = false, features = [] }
